### ISSUE TITLE
Diploid assembly strategy by using 10x-linked reads and Pacbio HiFi

### ISSUE THREAD

**Issue by ClarenceHsiang** [slimsuite/diploidocus#2]
Dear diploidocus developer team:

Good morning.

As shown in topic, we current datasets are 10x linked reads and Pacbio Hifi, and the genome size is about 300 mb.

May I ask about the suggestion for diploid genome assembly by combining these genome datasets in diploidocus?

Thank you very much 

Sincerely,

Clarence

**Comment by slimsuite** [comment]
Hi Clarence,
I would suggest assembling your HiFi data (if depth is good enough) with something like hifiasm and scaffolding with the 10x data (e.g. ARCS). Diploidocus can then be used to remove low-quality scaffolds and rogue haplotigs. Happy to give more advice and help run Diploidocus if you want to email me at richard.edwards@unsw.edu.au.
Best wishes,
Rich
