### ISSUE TITLE
Problems with installation of dependencies

### ISSUE THREAD

**Issue by BirdmanRidesAgain** [slimsuite/diploidocus#3]
Hi,
I'm trying to run the dipcycle and gapfill modules of diploidocus, but I'm having trouble wrangling the dependencies into shape. I created a conda environment running on python 2.7 in which to run diploidocus.py, which seemed to work, but certain dependencies on conda (eg, R and purge_haplotigs), don't seem to be able to correctly install with that python environment active.
I also attempted to run diploidocus in 3.0, and to install it as part of the SlimSuite package of tools, but neither of those seemed to work. 
`python diploidocus.py` threw syntax errors in python 3.X.X, and the current Slimsuite respository hosted on GitHub doesn't seem to even have diploidocus at the moment.

I'd appreciate any help you can give in getting this running - it looks like an incredibly powerful protocol to run for de novo assemblies.

**Comment by slimsuite** [comment]
Hi. 
Thanks for letting me know. I am slowly transitioning the code to be Python 3.x compatible, but will try to accelerate this - I will be needing to set up everything on a new system myself using virtual environments, so will probably run into the same problems. (I currently run it on a system on which R and purge_haplotigs are loaded as modules rather than through conda.) I think it should be possible to have both python 2.x and python 3.x running at the same time, but I have never tried this through conda environments.
Rich

**Comment by slimsuite** [comment]
Hi @BirdmanRidesAgain. I have updated the repo to the latest version, v1.3.1. Can you see if the Python3 issues are still happening? (I've not tested it through the whole pipeline in python3.)

Do I understand that even R will not install correctly for you in conda? If it does, you can also try the new purgehap=diploidocus mode, which should bypass the need for purge_haplotigs, but might not be quite as accurate.

**Comment by BirdmanRidesAgain** [comment]
Thanks for getting back to me.

First- I don't think you actually can have Python 2.x and 3.x running at the same time in the same conda environment - at least, when I try, I'm just prompted to let one version supercede the other. It might be possible if you constructed two Python packages with different names, or if there was an option in the python command itself to swap between the two, but vanilla conda won't allow you to do so.

Secondly, R(v.4.1.3) will install for me in a python (v.3.10.5) environment, as will most of the other dependencies. My uneducated guess is that there might have been a conflict between the later R packages and Python 2.x, which might be resolvable if you specify a particular version of R. I haven't tested that, though.

When I attempt to rerun `python diploidocus.py` using the new repository, I get the following input back:

```
File "../../../../tools/diploidocus-master/code/diploidocus.py", line 480, in <module>
    import rje, rje_db, rje_forker, rje_obj, rje_rmd, rje_seqlist, rje_sequence, rje_paf #, rje_genomics
ImportError: No module named 'rje'
```
So, we seem to be getting closer, but I'm not sure how to import that particular module to the Python environment.

**Comment by slimsuite** [comment]
That's odd, because it should just pickup the rje.py module from the `code` directory:

```
% git clone https://github.com/slimsuite/diploidocus.git
Cloning into 'diploidocus'...
remote: Enumerating objects: 432, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 432 (delta 59), reused 65 (delta 36), pack-reused 321
Receiving objects: 100% (432/432), 5.37 MiB | 4.09 MiB/s, done.
Resolving deltas: 100% (276/276), done.
% python3 diploidocus/code/diploidocus.py --version
1.3.1
% python3 diploidocus/code/diploidocus.py          
>>> Python 3.x detected but not fully supported. Please report odd behaviour <<<

Diploidocus V1.3.1 run: Wed Nov  2 20:40:23 2022

  ##############################################################################################################################
  #|#> Diploidocus version 1.3.1 : Diploid genome assembly analysis toolkit.                                                <#|#
  #|#>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<#|#
  #|#> Copyright (c) 2017 Dr Richard J. Edwards. <#~#> Last Modified: May 2022                                              <#|#
  #|#>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<#|#
  #|#> Disclaimer: Diploidocus comes with ABSOLUTELY NO WARRANTY;                                                           <#|#
  #|#>   This is free software, and you are welcome to redistribute it;                                                     <#|#
  #|#>   For details see attached license file (gnu_general_public_license.txt)                                             <#|#
  #|#>   or http://www.gnu.org/copyleft/gpl.html.                                                                           <#|#
  #|#>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<#|#
  #|#> Tidy Citation: Chen SH et al. & Edwards RJ (2022): Mol. Ecol. Res. (doi: 10.1111/1755-0998.13574)                    <#|#
  #|#> Nala Citation:  Edwards RJ et al. (2021), BMC Genomics [PMID: 33726677]                                              <#|#
  #|#> DipNR Citation: Stuart KC, Edwards RJ et al. (preprint), bioRxiv 2021.04.07.438753; (doi: 10.1101/2021.04.07.438753) <#|#
  #|#> Please raise bugs or questions at https://github.com/slimsuite/diploidocus.                                          <#|#
  #|#> NOTE: telomere finding rules are based on https://github.com/JanaSperschneider/FindTelomeres                         <#|#
  #|#> It is pointless to procrastinate because an annotating kitten bathes in plenty                                       <#|#
  ##############################################################################################################################


Append file: /Users/redwards/Temp/diploidocus.log

#WARN	00:00:00	Python 3.x detected but not fully supported. Please report odd behaviour.     
#VIO	00:00:00	Verbosity: 1; Interactivity: 0.
#NOTE	00:00:00	Interactivity could cause problems for queued HPC jobs etc. If so, set i=-1.
#BASE	00:00:00	Output file basename: diploidocus
#MODE	00:00:00	diploidocus

No file name given: Input filename? (Blank to exit.): 
```

Can you check that all the code is there?

**Comment by slimsuite** [comment]
FWIW, I have python 2.x and 3.x installed on my HPC system and `python` calls 2.x while `python3` calls 3.x. I didn't set it up though. You can also choose which python to run by specifying the full path, e.g.

```
$ /apps/python/2.7.15/bin/python tools/diploidocus.py --version
```

**Comment by BirdmanRidesAgain** [comment]
Yep - l looked in the code subdirectory of "diploidocus-master" (I just downloaded it as a tarball and manually unpacked/uploaded it rather than the git clone command  - maybe that's why?), and I have both "rje_py2.py_ and "rje_py3.py".

Good to know you can specify versions of python not contained within your current conda environment. That makes a lot more sense.

**Comment by slimsuite** [comment]
Those are different files. You should have `rje.py` in there too. That's the file that it's reporting as missing.

**Comment by BirdmanRidesAgain** [comment]
I do not have rje.py, which, I suppose answers why diploidocus can't import it. Adding it to the code directory seems to have cleared up the error.

**Comment by slimsuite** [comment]
That's good. Am I OK to close the issue?

**Comment by BirdmanRidesAgain** [comment]
I believe so. Thanks!
